Fourth milestone completed - Readme & Game Instructions
xtrmdarc/Tic-tac-toe pull request #4
Opened 2020-02-28 21:25 UTC by xtrmdarc

We kindly request a code review for our fourth milestone, in which we format the readme to include : 

- Instructions on how to play the game
- Instructions on how to run the game
- A live version of the game

Thank you.

2020-02-29 20:01 UTC, euqueme requested changes
> ### Pull Request under the review by Maria Eugenia Queme P. (TSE)

### Hello @xtrmdarc and @ivanid22 :balloon: :lollipop: 

### This project is very professional :star2: you should feel very proud of yourselves, :1st_place_medal:  :1st_place_medal: you actually gave me an idea to make a live demo for my own tic-tac-toe game :smile:  :v: 

### I have a couple of changes for your README file so please address them in the comments below :point_down: 

## [OPTIONAL]

- [x] [OPTIONAL]this wasn't spotted in the previous milestones so I won't request it as mandatory but your game lets you have empty player names, so let's add the validation to correct this

![image](https://user-images.githubusercontent.com/52209067/75614171-a03f1000-5afb-11ea-8279-1cf8399916fa.png)

### That's it, team! :raised_hands: 

### Please :pray:  do the changes :man_technologist: :man_technologist: and submit back for a code review when you are done :memo: 

Happy coding! :rocket: 

Any question? ask me on slack **@ Maru** :woman_technologist: 

PROJECT STATUS: REQUESTED CHANGES :traffic_light:

2020-02-29 20:01 UTC, euqueme commented on README.md
> +This is a two-player game. Each player takes turns making placing a token on the board until there's a winner or a draw match.
'making placing a token' delete the word 'making' on line #7

2020-02-29 20:01 UTC, euqueme commented on README.md
> +First of all, you need to have the game files in your computer. You can get them by cloning this repository.
they can also just download the repo so please explain how

2020-02-29 20:49 UTC, ivanid22 commented on README.md
> +First of all, you need to have the game files in your computer. You can get them by cloning this repository.
Thanks for your feedback Maria, we just pushed two commits with the fixes you requested

2020-03-01 06:25 UTC, whiz25 approved these changes
## Congz :clap: 
Your README looks professional and it's a :+1:  from me. Merge and proceed.

### Martin Afani

2020-03-02 14:50 UTC, merged